name: Build macOS app (PyInstaller)

on:
  workflow_dispatch:

jobs:
  build-macos-arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow
          pyinstaller --onefile --windowed --name "fotoyuklecalisan_1" fotoyuklecalisan_1.py
          pyinstaller --onefile --windowed --name "vskbiometrikyukle"  vskbiometrikyukle.py
          pyinstaller --onefile --windowed --name "ana_sayfa" \
            --add-data "atesanit.png:." \
            --add-data "ataturk.png:." \
            --add-data "dist/fotoyuklecalisan_1:fotoyuklecalisan_1" \
            --add-data "dist/vskbiometrikyukle:vskbiometrikyukle" \
            ana_sayfa.py
      - run: cd dist && zip -r ana_sayfa_macOS_arm64.zip ana_sayfa.app
      - uses: actions/upload-artifact@v4
        with:
          name: ana_sayfa_macOS_arm64
          path: dist/ana_sayfa_macOS_arm64.zip
